[workspace]
members = [
    "./lib-levelcrush-macros",
    "./lib-levelcrush",
    "./lib-destiny",
    "./service-accounts",
    "./service-destiny",
    "./app-destiny/src-tauri",
]

[workspace.dependencies]
tokio = { version = "1.25.0", features = ["full", "tracing"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.103" }
serde_urlencoded = { version = "0.7.1" }
serde_repr = { version = "0.1.14" }
serde_yaml = { version = "0.9.25" }
sqlx = { version = "0.7.1", features = [
    "sqlite",
    "bigdecimal",
    "runtime-tokio-rustls",
    "macros",
    "chrono",
], default_features = false }
bigdecimal = { version = "0.3.1", features = ["serde"] } # compat with sqlx
chrono = { version = "0.4.26", features = ["serde", "default"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
anyhow = "1.0.72"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
tracing-test = "0.2.4"
rand = "0.8.5"
futures = "0.3.28"
reqwest = { version = "0.11.18", features = [
    "json",
    "rustls-tls",
], default_features = false }
clap = { version = "4.3.17", features = ["derive"] }
md5 = { version = "0.7.0" }
base64 = { version = "0.21.0" }
urlencoding = { version = "2.1.2" }
